Fix FossifyOrg/#28 (Missing contacts)
FossifyOrg/Commons pull request #55
Opened 2024-06-28 13:24 UTC by czarnyckm

Fix FossifyOrg/#28 (Missing contacts)
According to doc ContentResolver.getIsSyncable returns value >0 if it is syncable, 0 if not, and <0 if the state isn't known yet.
see also
https://github.com/FossifyOrg/Phone/issues/28#issuecomment-1938635900

#### What is it?
- [x ] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)
Fixes  FossifyOrg/#28

#### Relies on the following changes

- 

#### Acknowledgement
- [ x] I read the [contribution guidelines](https://github.com/FossifyOrg/Commons/blob/master/CONTRIBUTING.md).

2024-06-28 13:42 UTC, Aga-C commented
Fixes https://github.com/FossifyOrg/Phone/issues/28 and fixes  https://github.com/FossifyOrg/Contacts/issues/83.

2024-08-06 20:44 UTC, Honk2 commented
imho this is an important fix, because the app it not usable without.
When will it be merged? What is the reason that it is not merged yet?
Is there anything that needs to be done? I did not find anything about the procedures in the repo.

2024-08-08 15:26 UTC, Kasi07 commented
I agree. Is testing needed for this to be merged? In that case I would be open to test if someone could provide the apk.

2024-08-09 19:37 UTC, naveensingh commented
Unfortunately I haven't had the time to work on this and some other important issues in Fossify (got super busy recently with some personal but unexpected matters). Hopefully I'll have some time for work after the weekend.

2024-08-26 11:26 UTC, Groctel requested changes
The correct check should be `ContentResolver.getIsSyncable(it, AUTHORITY) > 0` given the meaning of the function's retcodes: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/content/SyncStorageEngine.java;l=260-289

2024-08-26 12:51 UTC, czarnyckm commented
I fix the check `ContentResolver.getIsSyncable(it, AUTHORITY) > 0 `

2024-08-30 06:54 UTC, jrd commented
@naveensingh can you review and merge it please? I cannot use the app for months…

2024-08-30 08:01 UTC, naveensingh commented
I'm aware that this is an important issue for many but I'm currently stuck in a hospital. I'll try to release an update as soon as I have some free time.

2024-08-30 08:41 UTC, jrd commented
Ok I understand, thank you for the quick answer.

2024-08-30 08:49 UTC, Groctel commented
@naveensingh Your wellbeing always comes first. Take all the time you need, but still get better soon ❤️❤️❤️

2024-09-03 11:14 UTC, merged

2024-09-03 12:43 UTC, naveensingh commented
Apparently, `getIsSyncable()` returns 0 i.e. `NOT_SYNCABLE` when Google Play Services is disabled.

2024-09-03 15:47 UTC, cpontvieux-systra commented
That would explain the loosy doc (and variable name). It has meaning only if you have the Google Play Service running.